env:
  TERM: alacritty

colors:
  primary:
    background: "#282a36"
    foreground: "#f8f8f2"
    bright_foreground: "#ffffff"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"
    footer_bar:
      background: "#282a36"
      foreground: "#f8f8f2"
  hints:
    start:
      foreground: "#282a36"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#282a36"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: "#44475a"
  normal:
    black: "#21222c"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#bd93f9"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#f8f8f2"
  bright:
    black: "#6272a4"
    red: "#ff6e6e"
    green: "#69ff94"
    yellow: "#ffffa5"
    blue: "#d6acff"
    magenta: "#ff92df"
    cyan: "#a4ffff"
    white: "#ffffff"

# Font
font:
  size: 12
  normal:
    family: "HackGen Console NF"
    style: Regular
  bold:
    family: "HackGen Console NF"
    style: Bold
  italic:
    family: "HackGen Console NF"
    style: Italic
  bold_italic:
    family: "HackGen Console NF"
    style: Bold Itali

window:
  opacity: 0.8

key_bindings:
  - { key: K, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  - { key: K, mods: Command, mode: ~Vi|~Search, action: ClearHistory }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Command, action: DecreaseFontSize }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: C, mods: Command, mode: Vi|~Search, action: ClearSelection }
  - { key: H, mods: Command, action: Hide }
  - { key: H, mods: Command|Alt, action: HideOtherApplications }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }
  - { key: F, mods: Command, mode: ~Search, action: SearchForward }
  - { key: B, mods: Command, mode: ~Search, action: SearchBackward }
